import { NextResponse } from "next/server";
import clientPromise from "@/lib/mongodb";
import { Product, Category, Settings, User } from "@/types";

const categories: Omit<Category, "_id">[] = [
  { name: "Dinner", nameAr: "عشاء", slug: "dinner", order: 1 },
  { name: "Arabic", nameAr: "عربي", slug: "arabic", order: 2 },
  { name: "Italian", nameAr: "إيطالي", slug: "italian", order: 3 },
  { name: "Asian", nameAr: "آسيوي", slug: "asian", order: 4 },
  { name: "American", nameAr: "أمريكي", slug: "american", order: 5 },
  { name: "Seafood", nameAr: "مأكولات بحرية", slug: "seafood", order: 6 },
  { name: "Grills", nameAr: "مشويات", slug: "grills", order: 7 },
  { name: "Soups", nameAr: "شوربات", slug: "soups", order: 8 },
];

const products: Omit<Product, "_id">[] = [
  {
    name: "Eggs Benedict",
    nameAr: "بيض بينديكت",
    description: "Poached eggs on toasted English muffin with smoked ham and velvety hollandaise sauce.",
    descriptionAr: "بيض مسلوق على خبز إنجليزي محمص مع لحم مدخن وصلصة هولنديز كريمية.",
    price: 48,
    calories: 480,
    cookTime: 15,
    category: "dinner",
    image: "https://images.unsplash.com/photo-1608039829572-f0d3c6e05a4c?w=400&h=300&fit=crop",
    ingredients: ["Poached eggs", "English muffin", "Hollandaise", "Smoked ham", "Chives"],
    ingredientsAr: ["بيض مسلوق", "خبز إنجليزي", "صلصة هولنديز", "لحم مدخن", "ثوم معمر"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Shakshuka",
    nameAr: "شكشوكة",
    description: "Eggs poached in spiced tomato and pepper sauce, served with warm bread.",
    descriptionAr: "بيض مسلوق في صلصة طماطم وفلفل متبلة، يقدم مع خبز دافئ.",
    price: 42,
    calories: 380,
    cookTime: 20,
    category: "arabic",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=400&h=300&fit=crop",
    ingredients: ["Eggs", "Tomatoes", "Bell peppers", "Onions", "Spices"],
    ingredientsAr: ["بيض", "طماطم", "فلفل حلو", "بصل", "بهارات"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Buttermilk Pancakes",
    nameAr: "فطائر اللبن",
    description: "Fluffy buttermilk pancakes with maple syrup, fresh berries, and whipped cream.",
    descriptionAr: "فطائر لبن هشة مع شراب القيقب والتوت الطازج والكريمة المخفوقة.",
    price: 32,
    calories: 520,
    cookTime: 12,
    category: "american",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
    ingredients: ["Buttermilk", "Flour", "Maple syrup", "Berries", "Whipped cream"],
    ingredientsAr: ["لبن رائب", "دقيق", "شراب القيقب", "توت", "كريمة مخفوقة"],
    discount: 15,
    discountEndsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    name: "Avocado Toast",
    nameAr: "توست الأفوكادو",
    description: "Smashed avocado on artisan sourdough with poached egg and microgreens.",
    descriptionAr: "أفوكادو مهروس على خبز العجين المخمر مع بيض مسلوق وخضروات صغيرة.",
    price: 45,
    calories: 420,
    cookTime: 10,
    category: "dinner",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop",
    ingredients: ["Avocado", "Sourdough bread", "Poached egg", "Microgreens", "Olive oil"],
    ingredientsAr: ["أفوكادو", "خبز مخمر", "بيض مسلوق", "خضروات صغيرة", "زيت زيتون"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Full English Breakfast",
    nameAr: "فطور إنجليزي كامل",
    description: "Classic English breakfast with eggs, bacon, sausage, beans, toast, mushrooms and tomatoes.",
    descriptionAr: "فطور إنجليزي كلاسيكي مع بيض ولحم مقدد ونقانق وفاصوليا وخبز محمص وفطر وطماطم.",
    price: 62,
    calories: 850,
    cookTime: 25,
    category: "dinner",
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&h=300&fit=crop",
    ingredients: ["Eggs", "Bacon", "Sausage", "Beans", "Toast", "Mushrooms", "Tomatoes"],
    ingredientsAr: ["بيض", "لحم مقدد", "نقانق", "فاصوليا", "خبز محمص", "فطر", "طماطم"],
    discount: 0,
    isActive: true,
  },
  {
    name: "French Toast",
    nameAr: "توست فرنسي",
    description: "Brioche French toast with cinnamon, vanilla, maple syrup, and seasonal fruits.",
    descriptionAr: "توست فرنسي بريوش مع قرفة وفانيليا وشراب القيقب وفواكه موسمية.",
    price: 40,
    calories: 580,
    cookTime: 15,
    category: "american",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&h=300&fit=crop",
    ingredients: ["Brioche", "Eggs", "Cinnamon", "Vanilla", "Maple syrup", "Fruits"],
    ingredientsAr: ["بريوش", "بيض", "قرفة", "فانيليا", "شراب القيقب", "فواكه"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Club Sandwich",
    nameAr: "كلوب ساندويتش",
    description: "Triple-decker with grilled chicken, bacon, lettuce, tomato, and egg with fries.",
    descriptionAr: "ساندويتش ثلاثي الطبقات مع دجاج مشوي ولحم مقدد وخس وطماطم وبيض مع بطاطس مقلية.",
    price: 55,
    calories: 720,
    cookTime: 18,
    category: "american",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop",
    ingredients: ["Chicken", "Bacon", "Lettuce", "Tomato", "Egg", "Fries"],
    ingredientsAr: ["دجاج", "لحم مقدد", "خس", "طماطم", "بيض", "بطاطس مقلية"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Beef Burger Deluxe",
    nameAr: "برجر لحم فاخر",
    description: "Premium Angus beef patty with cheddar, caramelized onions, pickles, and truffle fries.",
    descriptionAr: "لحم أنجوس فاخر مع جبنة شيدر وبصل مكرمل ومخلل وبطاطس بالكمأة.",
    price: 54,
    calories: 920,
    cookTime: 20,
    category: "grills",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    ingredients: ["Angus beef", "Cheddar", "Onions", "Pickles", "Truffle fries"],
    ingredientsAr: ["لحم أنجوس", "جبنة شيدر", "بصل", "مخلل", "بطاطس بالكمأة"],
    discount: 20,
    discountEndsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    name: "Margherita Pizza",
    nameAr: "بيتزا مارجريتا",
    description: "Classic Italian pizza with San Marzano tomatoes, fresh mozzarella, and basil.",
    descriptionAr: "بيتزا إيطالية كلاسيكية مع طماطم سان مارزانو وموزاريلا طازجة وريحان.",
    price: 58,
    calories: 680,
    cookTime: 15,
    category: "italian",
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&h=300&fit=crop",
    ingredients: ["Pizza dough", "San Marzano tomatoes", "Mozzarella", "Basil", "Olive oil"],
    ingredientsAr: ["عجينة بيتزا", "طماطم سان مارزانو", "موزاريلا", "ريحان", "زيت زيتون"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Spaghetti Carbonara",
    nameAr: "سباغيتي كاربونارا",
    description: "Traditional Roman pasta with guanciale, egg yolk, pecorino, and black pepper.",
    descriptionAr: "باستا رومانية تقليدية مع غوانسيالي وصفار البيض وجبنة بيكورينو وفلفل أسود.",
    price: 52,
    calories: 620,
    cookTime: 18,
    category: "italian",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop",
    ingredients: ["Spaghetti", "Guanciale", "Egg yolk", "Pecorino", "Black pepper"],
    ingredientsAr: ["سباغيتي", "غوانسيالي", "صفار البيض", "بيكورينو", "فلفل أسود"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Pad Thai",
    nameAr: "باد تاي",
    description: "Stir-fried rice noodles with shrimp, tofu, peanuts, and tamarind sauce.",
    descriptionAr: "نودلز أرز مقلية مع جمبري وتوفو وفول سوداني وصلصة التمر الهندي.",
    price: 48,
    calories: 580,
    cookTime: 15,
    category: "asian",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=300&fit=crop",
    ingredients: ["Rice noodles", "Shrimp", "Tofu", "Peanuts", "Tamarind", "Bean sprouts"],
    ingredientsAr: ["نودلز أرز", "جمبري", "توفو", "فول سوداني", "تمر هندي", "براعم الفاصوليا"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Sushi Platter",
    nameAr: "طبق سوشي",
    description: "Assorted nigiri and maki rolls with salmon, tuna, and California roll.",
    descriptionAr: "تشكيلة نيجيري وماكي رولز مع سلمون وتونة وكاليفورنيا رول.",
    price: 85,
    calories: 450,
    cookTime: 25,
    category: "asian",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop",
    ingredients: ["Sushi rice", "Salmon", "Tuna", "Avocado", "Nori", "Wasabi"],
    ingredientsAr: ["أرز سوشي", "سلمون", "تونة", "أفوكادو", "نوري", "واسابي"],
    discount: 10,
    discountEndsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    name: "Grilled Salmon",
    nameAr: "سلمون مشوي",
    description: "Atlantic salmon fillet with lemon butter sauce, asparagus, and mashed potatoes.",
    descriptionAr: "فيليه سلمون أطلسي مع صلصة الليمون والزبدة والهليون والبطاطس المهروسة.",
    price: 72,
    calories: 520,
    cookTime: 22,
    category: "seafood",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
    ingredients: ["Salmon", "Lemon butter", "Asparagus", "Potatoes", "Herbs"],
    ingredientsAr: ["سلمون", "زبدة ليمون", "هليون", "بطاطس", "أعشاب"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Lobster Thermidor",
    nameAr: "لوبستر ثيرميدور",
    description: "Succulent lobster in creamy brandy sauce with gruyere cheese gratin.",
    descriptionAr: "كركند طري في صلصة براندي كريمية مع جراتان جبنة غرويير.",
    price: 125,
    calories: 680,
    cookTime: 35,
    category: "seafood",
    image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&h=300&fit=crop",
    ingredients: ["Lobster", "Brandy", "Cream", "Gruyere", "Mustard", "Herbs"],
    ingredientsAr: ["كركند", "براندي", "كريمة", "غرويير", "خردل", "أعشاب"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Lamb Kofta",
    nameAr: "كفتة لحم ضأن",
    description: "Spiced lamb skewers with tahini sauce, hummus, and warm pita bread.",
    descriptionAr: "أسياخ لحم ضأن متبلة مع صلصة الطحينة والحمص وخبز البيتا الدافئ.",
    price: 58,
    calories: 620,
    cookTime: 20,
    category: "arabic",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop",
    ingredients: ["Lamb", "Spices", "Tahini", "Hummus", "Pita bread"],
    ingredientsAr: ["لحم ضأن", "بهارات", "طحينة", "حمص", "خبز بيتا"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Chicken Shawarma",
    nameAr: "شاورما دجاج",
    description: "Marinated chicken with garlic sauce, pickles, and fresh vegetables in pita.",
    descriptionAr: "دجاج متبل مع صلصة الثوم والمخلل والخضروات الطازجة في خبز البيتا.",
    price: 38,
    calories: 480,
    cookTime: 15,
    category: "arabic",
    image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop",
    ingredients: ["Chicken", "Garlic sauce", "Pickles", "Vegetables", "Pita"],
    ingredientsAr: ["دجاج", "صلصة الثوم", "مخلل", "خضروات", "خبز بيتا"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Ribeye Steak",
    nameAr: "ستيك ريب آي",
    description: "Prime 300g ribeye with peppercorn sauce, grilled vegetables, and potato wedges.",
    descriptionAr: "ريب آي فاخر 300 جرام مع صلصة الفلفل الأسود والخضروات المشوية وأصابع البطاطس.",
    price: 98,
    calories: 850,
    cookTime: 25,
    category: "grills",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop",
    ingredients: ["Ribeye", "Peppercorn sauce", "Vegetables", "Potato wedges"],
    ingredientsAr: ["ريب آي", "صلصة الفلفل", "خضروات", "أصابع البطاطس"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Tom Yum Soup",
    nameAr: "شوربة توم يم",
    description: "Spicy Thai soup with shrimp, mushrooms, lemongrass, and kaffir lime.",
    descriptionAr: "شوربة تايلاندية حارة مع جمبري وفطر وعشب الليمون وورق الليمون.",
    price: 35,
    calories: 180,
    cookTime: 15,
    category: "soups",
    image: "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&h=300&fit=crop",
    ingredients: ["Shrimp", "Mushrooms", "Lemongrass", "Kaffir lime", "Chili"],
    ingredientsAr: ["جمبري", "فطر", "عشب الليمون", "ورق الليمون", "فلفل حار"],
    discount: 0,
    isActive: true,
  },
  {
    name: "French Onion Soup",
    nameAr: "شوربة البصل الفرنسية",
    description: "Caramelized onion soup with beef broth, gruyere crouton, and fresh thyme.",
    descriptionAr: "شوربة بصل مكرمل مع مرق اللحم وكروتون الغرويير والزعتر الطازج.",
    price: 32,
    calories: 320,
    cookTime: 20,
    category: "soups",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
    ingredients: ["Onions", "Beef broth", "Gruyere", "Bread", "Thyme"],
    ingredientsAr: ["بصل", "مرق اللحم", "غرويير", "خبز", "زعتر"],
    discount: 0,
    isActive: true,
  },
  {
    name: "Chicken Tikka Masala",
    nameAr: "دجاج تكا ماسالا",
    description: "Tender chicken in creamy tomato curry sauce with basmati rice and naan.",
    descriptionAr: "دجاج طري في صلصة كاري طماطم كريمية مع أرز بسمتي وخبز النان.",
    price: 52,
    calories: 680,
    cookTime: 25,
    category: "asian",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop",
    ingredients: ["Chicken", "Tomatoes", "Cream", "Spices", "Basmati rice", "Naan"],
    ingredientsAr: ["دجاج", "طماطم", "كريمة", "بهارات", "أرز بسمتي", "خبز النان"],
    discount: 0,
    isActive: true,
  },
];

const defaultSettings: Omit<Settings, "_id"> = {
  restaurantName: "Warwick Restaurant",
  restaurantNameAr: "مطعم ووريك",
  logo: "",
  heroTitle: "Food Menu",
  heroTitleAr: "قائمة الطعام",
  heroSubtitle: "Explore Our",
  heroSubtitleAr: "استكشف",
  phone: "+966 55 555 5555",
  whatsapp: "966555555555",
  email: "info@warwick.example",
  address: "123 Gourmet Avenue, Culinary District",
  addressAr: "123 شارع الذواقة، حي الطهي",
  openingHours: "Open Daily: 11:00 AM - 11:00 PM",
  openingHoursAr: "مفتوح يومياً: 11:00 ص - 11:00 م",
  facebookUrl: "https://facebook.com",
  instagramUrl: "https://instagram.com",
  tiktokUrl: "https://tiktok.com",
  welcomePopup: {
    enabled: true,
    title: "Eid Mubarak!",
    titleAr: "عيد مبارك!",
    subtitle: "Celebrate the festive season with us",
    subtitleAr: "احتفل معنا بالموسم المبارك",
    discountText: "20% OFF",
    discountTextAr: "خصم 20%",
    codeText: "Use code: EID2024",
    message: "Enjoy our special Eid feast menus with family & friends.",
    messageAr: "استمتع بقائمة العيد الخاصة مع العائلة والأصدقاء.",
  },
  dealsCountdown: {
    enabled: true,
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
};

const adminUser: Omit<User, "_id"> = {
  email: "abusayeedriday@gmail.com",
  password: "587710",
  name: "Admin",
  role: "admin",
  createdAt: new Date(),
};

export async function GET() {
  try {
    const client = await clientPromise;
    const db = client.db("warwick_restaurant");

    // Clear existing data
    await db.collection("categories").deleteMany({});
    await db.collection("products").deleteMany({});
    await db.collection("settings").deleteMany({});
    await db.collection("users").deleteMany({});

    // Insert categories
    await db.collection("categories").insertMany(categories);
    console.log("Categories seeded");

    // Insert products
    await db.collection("products").insertMany(products);
    console.log("Products seeded");

    // Insert settings
    await db.collection("settings").insertOne(defaultSettings);
    console.log("Settings seeded");

    // Insert admin user (password stored as plain text per user request)
    await db.collection("users").insertOne(adminUser);
    console.log("Admin user created");

    return NextResponse.json({
      success: true,
      message: "Database seeded successfully with bilingual data!",
      data: {
        categories: categories.length,
        products: products.length,
        settings: 1,
        users: 1,
      },
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to seed database" },
      { status: 500 }
    );
  }
}
