export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  calories: number;
  prepTime: number;
  servings: number;
  category: string;
  image: string;
  isPopular?: boolean;
  ingredients?: string[];
}

export const categories = [
  { id: "all", name: "All", icon: "🍽️" },

  { id: "breakfast", name: "Breakfast", icon: "🍳" },
  { id: "bakery", name: "Bakery & Pastry", icon: "🥐" },

  { id: "appetizers", name: "Appetizers", icon: "🥗" },
  { id: "soups", name: "Soups", icon: "🍲" },
  { id: "salads", name: "Salads", icon: "🥙" },

  { id: "main-course", name: "Main Course", icon: "🍛" },
  { id: "rice-dishes", name: "Rice Dishes", icon: "🍚" },
  { id: "pasta", name: "Pasta & Noodles", icon: "🍝" },
  { id: "pizza", name: "Pizza", icon: "🍕" },
  { id: "burgers", name: "Burgers & Sandwiches", icon: "🍔" },

  { id: "grills", name: "Grills & BBQ", icon: "🔥" },
  { id: "seafood", name: "Seafood", icon: "🦐" },
  { id: "steaks", name: "Steaks", icon: "🥩" },

  { id: "arabic", name: "Arabic Cuisine", icon: "🥙" },
  { id: "indian", name: "Indian Cuisine", icon: "🍛" },
  { id: "chinese", name: "Chinese Cuisine", icon: "🥡" },
  { id: "italian", name: "Italian Cuisine", icon: "🍝" },

  { id: "kids", name: "Kids Menu", icon: "🧒" },
  { id: "healthy", name: "Healthy Options", icon: "🥦" },

  { id: "desserts", name: "Desserts", icon: "🍰" },
  { id: "ice-cream", name: "Ice Cream", icon: "🍨" },

  { id: "hot-beverages", name: "Hot Beverages", icon: "☕" },
  { id: "cold-beverages", name: "Cold Beverages", icon: "🥤" },
  { id: "mocktails", name: "Mocktails", icon: "🍹" },
  { id: "fresh-juice", name: "Fresh Juice", icon: "🍊" },
];

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Arabian Mezze Platter",
    description:
      "A delightful assortment of hummus, baba ganoush, falafel, and fresh pita bread with tahini sauce.",
    price: 85,
    calories: 420,
    prepTime: 15,
    servings: 2,
    category: "appetizers",
    image: "/arabian-mezze-platter-with-hummus-falafel.jpg",
    isPopular: true,
    ingredients: [
      "Chickpeas",
      "Eggplant",
      "Tahini",
      "Olive Oil",
      "Fresh Herbs",
    ],
  },
  {
    id: "2",
    name: "Lamb Kabsa",
    description:
      "Traditional Saudi rice dish with tender lamb, aromatic spices, and toasted almonds.",
    price: 145,
    calories: 680,
    prepTime: 45,
    servings: 1,
    category: "main-course",
    image: "/lamb-kabsa-saudi-rice-dish.jpg",
    isPopular: true,
    ingredients: ["Lamb", "Basmati Rice", "Cardamom", "Saffron", "Almonds"],
  },
  {
    id: "3",
    name: "Grilled Hammour",
    description:
      "Fresh local hammour fish grilled to perfection with lemon herb butter and seasonal vegetables.",
    price: 165,
    calories: 380,
    prepTime: 25,
    servings: 1,
    category: "seafood",
    image: "/grilled-hammour-fish-with-herbs.jpg",
    ingredients: [
      "Hammour Fish",
      "Lemon",
      "Butter",
      "Fresh Herbs",
      "Vegetables",
    ],
  },
  {
    id: "4",
    name: "Mixed Grill Platter",
    description:
      "Succulent lamb chops, chicken shish, and beef kofta served with rice and grilled vegetables.",
    price: 195,
    calories: 850,
    prepTime: 35,
    servings: 2,
    category: "grills",
    image: "/mixed-grill-platter-middle-eastern.jpg",
    isPopular: true,
    ingredients: ["Lamb", "Chicken", "Beef", "Spices", "Vegetables"],
  },
  {
    id: "5",
    name: "Shrimp Machboos",
    description:
      "Fragrant spiced rice with jumbo shrimp, caramelized onions, and traditional Gulf spices.",
    price: 135,
    calories: 520,
    prepTime: 30,
    servings: 1,
    category: "seafood",
    image: "/shrimp-machboos-rice-dish.jpg",
    ingredients: ["Jumbo Shrimp", "Rice", "Onions", "Loomi", "Bezar"],
  },
  {
    id: "6",
    name: "Fattoush Salad",
    description:
      "Crispy pita chips with fresh vegetables, pomegranate seeds, and tangy sumac dressing.",
    price: 55,
    calories: 280,
    prepTime: 10,
    servings: 1,
    category: "appetizers",
    image: "/fattoush-salad-lebanese.jpg",
    ingredients: ["Lettuce", "Tomatoes", "Cucumber", "Pita", "Sumac"],
  },
  {
    id: "7",
    name: "Chicken Mandi",
    description:
      "Slow-cooked chicken with fragrant rice, cooked in traditional underground oven style.",
    price: 125,
    calories: 620,
    prepTime: 40,
    servings: 1,
    category: "main-course",
    image: "/chicken-mandi-yemeni-rice.jpg",
    ingredients: ["Chicken", "Rice", "Cardamom", "Cinnamon", "Bay Leaves"],
  },
  {
    id: "8",
    name: "Kunafa",
    description:
      "Golden crispy vermicelli pastry filled with sweet cheese and drizzled with rose syrup.",
    price: 65,
    calories: 450,
    prepTime: 20,
    servings: 1,
    category: "desserts",
    image: "/kunafa-middle-eastern-dessert.jpg",
    isPopular: true,
    ingredients: ["Vermicelli", "Cheese", "Rose Water", "Pistachios", "Sugar"],
  },
  {
    id: "9",
    name: "Um Ali",
    description:
      "Creamy Egyptian bread pudding with nuts, raisins, and coconut, served warm.",
    price: 55,
    calories: 380,
    prepTime: 15,
    servings: 1,
    category: "desserts",
    image: "/um-ali-egyptian-dessert.jpg",
    ingredients: ["Puff Pastry", "Milk", "Cream", "Nuts", "Raisins"],
  },
  {
    id: "10",
    name: "Arabic Coffee",
    description: "Traditional Saudi coffee with cardamom, served with dates.",
    price: 25,
    calories: 5,
    prepTime: 5,
    servings: 1,
    category: "beverages",
    image: "/arabic-coffee-dallah-with-dates.jpg",
    ingredients: ["Coffee Beans", "Cardamom", "Saffron"],
  },
  {
    id: "11",
    name: "Fresh Lemon Mint",
    description:
      "Refreshing blend of fresh lemons and mint leaves, lightly sweetened.",
    price: 30,
    calories: 80,
    prepTime: 5,
    servings: 1,
    category: "beverages",
    image: "/lemon-mint-drink-refreshing.jpg",
    ingredients: ["Lemon", "Mint", "Sugar", "Ice"],
  },
  {
    id: "12",
    name: "Beef Tenderloin Steak",
    description:
      "Premium beef tenderloin grilled to your preference, served with mushroom sauce.",
    price: 220,
    calories: 580,
    prepTime: 25,
    servings: 1,
    category: "grills",
    image: "/beef-tenderloin-steak-gourmet.jpg",
    ingredients: ["Beef Tenderloin", "Mushrooms", "Butter", "Thyme", "Garlic"],
  },
  // ================= NEW MENU ITEMS =================

  {
    id: "13",
    name: "Continental Breakfast Platter",
    description:
      "Scrambled eggs, sausages, hash browns, toast, and grilled tomatoes.",
    price: 75,
    calories: 550,
    prepTime: 15,
    servings: 1,
    category: "breakfast",
    image: "/looding.gif",
    ingredients: ["Eggs", "Sausage", "Potato", "Bread", "Tomato"],
  },
  {
    id: "14",
    name: "Pancakes with Maple Syrup",
    description: "Fluffy pancakes served with butter and maple syrup.",
    price: 45,
    calories: 430,
    prepTime: 12,
    servings: 1,
    category: "breakfast",
    image: "/looding.gif",
  },

  {
    id: "15",
    name: "Chocolate Croissant",
    description: "Buttery French croissant filled with dark chocolate.",
    price: 25,
    calories: 300,
    prepTime: 5,
    servings: 1,
    category: "bakery",
    image: "/looding.gif",
  },
  {
    id: "16",
    name: "Blueberry Muffin",
    description: "Soft baked muffin loaded with fresh blueberries.",
    price: 20,
    calories: 280,
    prepTime: 5,
    servings: 1,
    category: "bakery",
    image: "/looding.gif",
  },

  {
    id: "17",
    name: "Lentil Soup",
    description: "Traditional Middle Eastern lentil soup with cumin and lemon.",
    price: 35,
    calories: 220,
    prepTime: 15,
    servings: 1,
    category: "soups",
    image: "/looding.gif",
  },
  {
    id: "18",
    name: "Cream of Mushroom Soup",
    description: "Rich and creamy mushroom soup with herbs.",
    price: 40,
    calories: 260,
    prepTime: 15,
    servings: 1,
    category: "soups",
    image: "/looding.gif",
  },

  {
    id: "19",
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce, parmesan cheese, croutons, Caesar dressing.",
    price: 50,
    calories: 320,
    prepTime: 10,
    servings: 1,
    category: "salads",
    image: "/looding.gif",
  },
  {
    id: "20",
    name: "Greek Salad",
    description:
      "Tomatoes, cucumber, olives, feta cheese with olive oil dressing.",
    price: 48,
    calories: 290,
    prepTime: 10,
    servings: 1,
    category: "salads",
    image: "/looding.gif",
  },

  {
    id: "21",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice with tender chicken and spices.",
    price: 120,
    calories: 650,
    prepTime: 35,
    servings: 1,
    category: "rice-dishes",
    image: "/looding.gif",
  },
  {
    id: "22",
    name: "Vegetable Fried Rice",
    description: "Wok-tossed rice with mixed vegetables and soy sauce.",
    price: 65,
    calories: 420,
    prepTime: 20,
    servings: 1,
    category: "rice-dishes",
    image: "/looding.gif",
  },

  {
    id: "23",
    name: "Spaghetti Bolognese",
    description: "Classic Italian pasta with rich beef tomato sauce.",
    price: 95,
    calories: 580,
    prepTime: 25,
    servings: 1,
    category: "pasta",
    image: "/looding.gif",
  },
  {
    id: "24",
    name: "Fettuccine Alfredo",
    description: "Creamy parmesan sauce with grilled chicken.",
    price: 105,
    calories: 620,
    prepTime: 25,
    servings: 1,
    category: "pasta",
    image: "/looding.gif",
  },

  {
    id: "25",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil.",
    price: 85,
    calories: 700,
    prepTime: 20,
    servings: 1,
    category: "pizza",
    image: "/looding.gif",
  },
  {
    id: "26",
    name: "Pepperoni Pizza",
    description: "Loaded with pepperoni slices and mozzarella cheese.",
    price: 95,
    calories: 820,
    prepTime: 20,
    servings: 1,
    category: "pizza",
    image: "/looding.gif",
  },

  {
    id: "27",
    name: "Classic Beef Burger",
    description: "Juicy beef patty with lettuce, tomato, and cheese.",
    price: 75,
    calories: 650,
    prepTime: 15,
    servings: 1,
    category: "burgers",
    image: "/looding.gif",
  },
  {
    id: "28",
    name: "Club Sandwich",
    description: "Triple-layer sandwich with chicken, egg, and turkey.",
    price: 70,
    calories: 600,
    prepTime: 15,
    servings: 1,
    category: "burgers",
    image: "/looding.gif",
  },

  {
    id: "29",
    name: "Ribeye Steak",
    description: "Premium ribeye steak grilled to perfection.",
    price: 240,
    calories: 700,
    prepTime: 30,
    servings: 1,
    category: "steaks",
    image: "/looding.gif",
  },
  {
    id: "30",
    name: "T-Bone Steak",
    description: "Tender T-bone steak with herb butter.",
    price: 260,
    calories: 750,
    prepTime: 30,
    servings: 1,
    category: "steaks",
    image: "/looding.gif",
  },

  {
    id: "31",
    name: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces.",
    price: 110,
    calories: 600,
    prepTime: 30,
    servings: 1,
    category: "indian",
    image: "/looding.gif",
  },
  {
    id: "32",
    name: "Chicken Manchurian",
    description: "Spicy Indo-Chinese chicken in soy garlic sauce.",
    price: 90,
    calories: 520,
    prepTime: 25,
    servings: 1,
    category: "chinese",
    image: "/looding.gif",
  },

  {
    id: "33",
    name: "Vanilla Ice Cream",
    description: "Classic creamy vanilla ice cream scoop.",
    price: 25,
    calories: 210,
    prepTime: 5,
    servings: 1,
    category: "ice-cream",
    image: "/looding.gif",
  },
  {
    id: "34",
    name: "Chocolate Ice Cream",
    description: "Rich chocolate flavored ice cream.",
    price: 28,
    calories: 240,
    prepTime: 5,
    servings: 1,
    category: "ice-cream",
    image: "/looding.gif",
  },

  {
    id: "35",
    name: "Cappuccino",
    description: "Espresso with steamed milk foam.",
    price: 28,
    calories: 120,
    prepTime: 5,
    servings: 1,
    category: "hot-beverages",
    image: "/looding.gif",
  },
  {
    id: "36",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice.",
    price: 30,
    calories: 110,
    prepTime: 5,
    servings: 1,
    category: "fresh-juice",
    image: "/looding.gif",
  },
  {
    id: "37",
    name: "Strawberry Mojito",
    description: "Non-alcoholic mojito with strawberry and mint.",
    price: 35,
    calories: 140,
    prepTime: 5,
    servings: 1,
    category: "mocktails",
    image: "/looding.gif",
  },
  {
    id: "38",
    name: "Iced Latte",
    description: "Chilled espresso with milk and ice.",
    price: 30,
    calories: 150,
    prepTime: 5,
    servings: 1,
    category: "cold-beverages",
    image: "/looding.gif",
  },
];
